### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ghost** [kim0sun/glca#1]
Hi, Dr. Kim

I can't download this package. I am having this error: 
> install.packages("glca")
Installing package into ‘C:/Users/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘glca’
  These will not be installed

Can you please help me to fix it?

Thank you!

**Comment by kim0sun** [comment]
glca has been updated on March 9th, but the binary form is not available yet. Use following command to install package with source file.

> install.packages("glca", type = "source")

Or you can install binary form soon (maybe within this week).

Thank you.

**Comment by kim0sun** [comment]
> Hi, Dr. Kim
> 
> 
> 
> I can't download this package. I am having this error: 
> 
> > install.packages("glca")
> 
> Installing package into ‘C:/Users/Documents/R/win-library/3.5’
> 
> (as ‘lib’ is unspecified)
> 
> Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘glca’
> 
>   These will not be installed
> 
> 
> 
> 
> 
> Can you please help me to fix it?
> 
> 
> 
> Thank you!

glca has been updated on March 9th, but the binary form is not available yet. Use following command to install package with source file.

> install.packages("glca", type = "source")

Or you can install binary form soon (maybe within this week).

Thank you.

**Comment by ghost** [comment]
It worked! 
Thanks!

**Comment by ghost** [comment]
Well, I am trying to run the analysis as illustrated here: https://kim0sun.github.io/glca/index.html
Now I am having an error message that data set `gss08` is not found. 
Does it mean that package is not properly installed?
OR do you recommend waiting until the package is more stable?

Thanks,
Euijin

**Comment by ghost** [comment]
Sorry for the frequent question!
It seems like I wasn't able to load glca package. 
If I downloaded using the guideline that you gave me, it should work right?

**Comment by kim0sun** [comment]
Yes, it should work. 
Please let me know how the error appears during loading the package.

**Comment by ghost** [comment]
Yes it worked! It seems like that my R studio and R is out of date, so didn't properly install the package. 
Thank you for your work! and thank you for the wonderful package. I'm excited to apply this to my research :)

**Comment by ghost** [comment]
Hi, Dr. Kim 
By the way, do you have any plan to extend this package to LTA? That will be great!

**Comment by kim0sun** [comment]
You can fit LTA model with LMest package. By the way, i'm a Ph.D. student, not a doctor
