### ISSUE TITLE
parameters multiple group lca

### ISSUE THREAD

**Issue by ruser1234** [kim0sun/glca#10]
Hello,

I am not sure if this question is appropriate but I will try.
I am running a multipe group LCA and was asked to replicate my results in Mplus.The results for a lca without grouping variable are identical. But now I noticed that when running a multiple group LCA, Mplus has always one more parameter. I  guess therefore the Log-likelihood as well as BIC, AIC are different. However, the class prevalences in Mplus and glca are always identical. 
I am running a LCA with 6 variables (3 levels). Having three classes, there are 38 parameters. When adding a grouping variable with two groups, I get 40 parameters in glca and 41 parameters in Mplus. 
I am not that good in statistics. I am able to calculate the parameters for a model without a grouping variable but I am confused when adding a grouping variable. 

Does somebody have any ideas or can help me calcuate the parameters?

**Comment by kim0sun** [comment]
Hi,
Can you share the results in Mplus? 
I think 40 is correct in that situation.
