### ISSUE TITLE
Warning message: Since responses are different, deviance table does not printed.

### ISSUE THREAD

**Issue by Barryacoughlan** [kim0sun/glca#11]
Hi,

I am receiving the following issue "Since responses are different, deviance table does not printed".  Has the bug been fixed in the most recent release or is there a workaround for the released version? For reference, I have 22 items and am unable to use the development version on Github. 

Thanks so much,

Barry

**Comment by marcelo-pereira-pcst** [comment]
Same problem here

**Comment by kim0sun** [comment]
The version with the error corrected has been released.

Could you please try running the function and let me know if it works properly.
