### ISSUE TITLE
customize plot function

### ISSUE THREAD

**Issue by marcelo-pereira-pcst** [kim0sun/glca#12]
Hello, 

I would like to know how to fully customize the plot function. I'm trying to change the axis labels, rotate the x-axis tick marks by 90 degrees, and translate the title and legend into another language. I have read the function's documentation and noticed that it mentions "further arguments passed to or from other methods," but unfortunately, I couldn't find more information or examples to help me. Is it possible to get more guidance on how to proceed? Thank you in advance.

**Comment by AlexGareau** [comment]
You can access the fit indices directly from glca()$gof and plot them with ggplot()
For predicted values the results are glca()$param$rho$ALL
For class proportion values are glca()$param$gamma.

I used ggplot() to have more customization for plotting the results.

**Comment by kim0sun** [comment]
@AlexGareau Thank you for comment :)
