### ISSUE TITLE
gofglca() can't be provided a list of models

### ISSUE THREAD

**Issue by AlexGareau** [kim0sun/glca#13]
It would nice to not have to multiple arguments for each model to be compared with the gofglca() function.
Given that it is standard practice to test in increment the number of class as an enumeration procedure, it would be nice if one could just provide a list of models like this

`
LCA <- map(2:6, function(nclass){
  items %>% 
    glca(item(names(.)) ~ 1,
         data = .,
         nclass = nclass,
         verbose = T)
})
gofglca(LCA)
`

`gofglca()` return this error **Error in gofglca(LCA) : All objects should be glca outputs.**

but if I split it like this

`gofglca(LCA[[1]], LCA[[2]], LCA[[3]]) `
Then it works.

**Comment by kim0sun** [comment]
You can use list in develop version now! 
Thank you for error report!
