### ISSUE TITLE
Line plot for Item response probabilities by class

### ISSUE THREAD

**Issue by mikgoo** [kim0sun/glca#18]
*SOLVED*
I discovered that the glca package only displays line plots for dichotomous indicators. As I was working with nominal polytomous indicators I hade to first transform them into dummies in order to have probabilities graphically illustrated via a lineplot. 

*Original post*
Hi! 
When I prompt r to plot() the LCA object i only get bar charts for the Item response probabilities by class (one bar plot per indicator used in the formula). I would however like to see a line chart, similar to what is used to showcase the plot(glcaobject)-function in the vignette. I use R 4.4.0 and an up-to-date version of glca. 
Thank you! 

I get:
![bild](https://github.com/user-attachments/assets/36f97133-9d84-4858-9056-b54fe7ccfc51)

But would like to get:
![Namnlös](https://github.com/user-attachments/assets/053a5dd4-0c95-4ba5-9d0c-a314c3010a7c)

**Comment by kim0sun** [comment]
Yes, if you have another idea for plotting item response probabilities, please let me know :)
