### ISSUE TITLE
Plotting 

### ISSUE THREAD

**Issue by ghost** [kim0sun/glca#2]
Hi, Mr.Kim

I have a question regarding the plot function in LCA. 
When I run the LCA, it seems like that "Item Response Probabilities by Class" draw the plot using Rho(Y=1) value. 
Am I right?
1. I want to know Rho (Y=2) plot. 
Do you have an option for that?

2. Also, when creating "Class prevalences by Group" it seems like the labeling box on the right is not correct (color for Class 1 and Class 3 are the same. See the attached pic).
![Rplot](https://user-images.githubusercontent.com/10934962/112406770-c628eb00-8ce2-11eb-9001-4603ec02d9bc.jpeg)

3. Also, it seems like that the axis on the left is not stretching to 1. It doesn't have to be stretching to 1, but at least my class 1 has more than 50% of the people, I want to show them roughly how much percent of the people are classified as class 1. (See the second attached pic)
![Rplot2](https://user-images.githubusercontent.com/10934962/112406861-fec8c480-8ce2-11eb-9414-51edfd0698c5.jpeg)

Thank you!

Euijin

**Comment by kim0sun** [comment]
1. You can relevel the data as following code

> factor = factor(c("Y", "N", "Y"))
> relevel(factor, "Y")

2. This legend error will be modified at next version
3. You can make your own plot with result of the fitted function as following.

> mglca = glca(item(DEFECT, HLTH, RAPE, POOR, SINGLE, NOMORE) ~ 1,
>                       group = DEGREE, data = gss08, nclass = 3)
> marginal_prev = colMeans(do.call(rbind, mglca$posterior))
> barplot(marginal_prev)

**Comment by ghost** [comment]
Hi, Mr. Kim 

Thank you so much for your help. 
Can you please help me to solve #1?
If my code looks like this, 
mglcr_C3 = glca(item(CheckingAcc,	AFS,	CCrej, RA, Investmnt, AbsorbShock ) 
                ~  sknol + lmscore +khscore +hhinc+race_wh+edu+female1+employed +maritlivp+ agecat + FinSupChild,
                group = povstatus, data = finac, nclass = 3, verbose = FALSE, na.rm=TRUE)

What should I do it? For all items, they are binary (0 or 1, and I think it was set like this by program default: Rho Y=0 and Rho Y=1, and it drew item response probability for Rho Y=0, but I want to see for Rho Y=1.

Can you please help me to do this?

2. Also, is entropy not included in the summary() ???

3. I want to know the membership of each person. Can I creat a class membership variable? 

Thank you so much.

**Comment by ghost** [comment]
One more thing to report:
It seems like **_across the group,_** multinomial beta coefficient results are the same except for the intercept. 
Can you confirm this?

![image](https://user-images.githubusercontent.com/10934962/113088564-7bf4ad80-91ab-11eb-9c0e-e651027dcf1e.png)

**Comment by kim0sun** [comment]
@EuiJin 

Sorry for delayed reply
1. `summary` returns Rho parameters for both Y=0 and Y=1.
2. entropy is included in `summary()`
3. `mglcr_C3$posterior` returns list of posterior probabilities, so that you can predict class membership using
> lapply(mglcr_C3$posterior, function(x) apply(x, 1, which.max))
4. Among `glca` arguments, `coeff.inv` arguments determines whether the beta coefficients are equal across the groups or not.
