### ISSUE TITLE
beta weight

### ISSUE THREAD

**Issue by ghost** [kim0sun/glca#3]
Hi, Mr. Kim

I have a question regarding the beta weights.
Please see the attached image. 
Can beta be negative? Isn't it standardized logistic regression coefficient? 

![image](https://user-images.githubusercontent.com/10934962/113806078-49a4fc00-9727-11eb-8533-e325fc8bc634.png)

Thank you!

**Comment by kim0sun** [comment]
@EuiJin 

Sorry for delayed reply,
The beta parameter is not standardized. using `coef` function, you can obtain odds ratio for the beta parameters.

Youngsun
