### ISSUE TITLE
MLCA standard errors

### ISSUE THREAD

**Issue by andersbacklund** [kim0sun/glca#4]
Dear kim0sun,

When I add two clusters to my two-class model, the standard errors of my covariates become extremely small. Is this normal?

Thank you!

Anders

**Comment by kim0sun** [comment]
@andersbacklund 

Sorry for delayed response.
The R output seems weird. 
Could you install developing version of the `glca` package by following commands
> #install.packages("devtools")
> library(devtools)
> install_github("kim0sun/glca")

Please retry the same procedure of the analysis with developing version
Thank you.

Youngsun

**Comment by andersbacklund** [comment]
Sorry for the late reply. The results when running the development version are identical to those obtained from the CRAN version.

Best wishes,

Anders

**Comment by kim0sun** [comment]
Can I get your data and executable code for checking?

Best,

Youngsun

**Comment by andersbacklund** [comment]
Sorry again for the late reply. I have found the problem: it was due to a coding error on my part pertaining to the grouping variable.

Best wishes,

Anders
