### ISSUE TITLE
Ordinal level of variables in LCA?

### ISSUE THREAD

**Issue by VLounek** [kim0sun/glca#5]
Dear Mr. Kim,

I tried using your great package for multiple-group LCA. However, my manifest variables entering the model are not binary, but ordinal with five levels. When trying to compare the models with gofglca(), the output gives the following:

_In gofglca(own_celkem_lca2, own_celkem_lca3, test = "boot", seed = 1) :
  Since responses are different, deviance table does not printed._

Is it somehow possible to inlude non-binary variables in the models so the function can print a deviance table?
Or is there any other way to decide which model (without groups; with groups and measure.inv = T; or measure.inv = F) is the appropriate one?
 Thank you.

**Comment by kim0sun** [comment]
Fixed
