### ISSUE TITLE
Warning message: "Since responses are different, deviance table does not print"

### ISSUE THREAD

**Issue by thorpej21** [kim0sun/glca#7]
Professor Kim: I am testing the measurement invariance of a latent class analysis of 26 binary items. I am first running a series of LCA models to determine the optimal number of latent classes. For theoretical reasons, we believe the optimal number is either 6 or 7 classes.

I have successfully run the competing models.

lca6 <-glca(f, data=df, nclass=6, seed=1)
lca7 <-glca(f, data=df, nclass=7, seed=1)

I am now trying to use "gofglca" using test="boot".
goftest <-gofglca(lca6, lca7, test="boot", seed=1)

I get a Goodness of Fit Table. However, I get the following warning message: "Since responses are different, deviance table does not print".

I am confused because these are the exact same samples. Could you please help me understand this warning message?

Thank you

**Comment by kim0sun** [comment]
There is a bug in released version of the package when the formula is too long.
Using developing package, you can use long formula.
Sorry to confuse you.

```
library(devtools)
install_github("kim0sun/glca")
```

**Comment by Barryacoughlan** [comment]
Hi,

I am also receiving this issue. Has the bug been fixed in the most recent release or is there a workaround for the released version? For reference, I have 22 items. 

Thanks so much,

Barry
