### ISSUE TITLE
Extracting Class or Clusters as dataframe 

### ISSUE THREAD

**Issue by Wentemi** [kim0sun/glca#8]
Hi Prof Sun, 
Thank you for your wonderful package.  After running  the model is there a way of extracting  the predicted class for observation ? 
I tried using the  max probability from the `lca$posterior` matrix to classify  for each observation, it doesn't seem to be right. 
Any  points will be appreciated.

**Comment by kim0sun** [comment]
You can use lca$posterior
But the object can be a list of matrix.
Thus, you should assign class each matrix separately.
Note following command:

```
lapply(lca$posterior, apply, 1, which.max)
```

If the command fails, please show me your full code. Thank you.

**Comment by sirwentemi** [comment]
Thank you very much it worked perfectly.
