### ISSUE TITLE
Support for the three-step (bias adjusted) method for auxiliary variables

### ISSUE THREAD

**Issue by sam-crawley** [kim0sun/glca#9]
Hello,

Thanks for providing an excellent module.

However, I was wondering if you would be interested in adding support for the three step method of handling covariates or distal outcome variables? (See [this article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8247311/) for a good overview). This method has the advantage that the covariates don't alter the latent class measurement model, which generally makes it easier to use and allows for a greater number of covariates to be added.

The first step of the method involves fitting a LCA model without covariates.

The second step requires calculating probabilities for the "most likely class". These can be fairly straightforwardly calculated from the posterior class probabilities provided by glca.

The third step involves fitting a LCA model with the covariates, but based on the most likely class probabilities calculated in step three. From my understanding (which is undoubtedly not complete!) this requires fixing the class probabilities to specified values. I don't believe glca currently supports this.

Would you have any interest in adding this functionality? I'm happy to help where possible.

Thanks.

**Comment by kim0sun** [comment]
I am totally interested in three step approach. But I have no plans to add three step approach on glca.

Instead, I will adopt three step approach for external variables in my on-going R package.
This R package aims more complex categorical latent variable models. (LCPA, JLCA, or JLCPA)

If you are interested in those models, please contact me via kim0sun@korea.ac.kr.

Thank you.

**Comment by sam-crawley** [comment]
Thanks, I'll get in touch.
